vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        gite_photos:
            uri_prefix: /images/gite_photos
            upload_destination: '%kernel.project_dir%/public/images/gite_photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer